#!/bin/bash

#PBS -N preprocess
#PBS -l nodes=1:ppn=1
#PBS -l vmem=1gb
#PBS -l walltime=12:00:00
#PBS -j oe
#PBS -m ae
#PBS -V

DATA_RAW=/srv/scratch/ppcs/data-raw/ 
GRAPHS=/srv/scratch/ppcs/pickle/graphs/

cd $DATA_RAW
for FILENAME in *.csv 
do 
    CSV="$DATA_RAW$FILENAME"
    export CSV GRAPHS FILENAME
    echo "Submitting $FILENAME"
    qsub /srv/scratch/ppcs/doctor-patient-networks/pbs/build-graph.pbs 
done 
